---
title: "class09"
author: "Zhuohang Wu"
date: "February 7, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
wisc.df <- read.csv("WisconsinCancer.csv")

wisc.data <- as.matrix(wisc.df[,3:32])
row.names(wisc.data) <- wisc.df$id
diagnosis <- as.numeric(wisc.df$diagnosis)
table(wisc.df$diagnosis)
View(diagnosis)
```

```{r}
tmp <- rep(0,nrow(wisc.df))
as.numeric(wisc.df$diagnosis=="M")
```

```{r}
cbind(diagnosis,wisc.df$diagnosis)
```

```{r}
colMeans(wisc.data)

apply(wisc.data,2,sd)


```

```{r}
wisc.pr <- prcomp(wisc.data, scale=TRUE)
summary(wisc.pr)
```

```{r}
biplot(wisc.pr)
```

```{r}
plot(wisc.pr$x[,1],wisc.pr$x[,2],col=diagnosis+1, xlab = "PC1",ylab = "PC2")
```

```{r}
varance <- wisc.pr$sdev^2
pve <- varance/sum(varance)*100
head(varance)
```


```{r}
barplot(pve, ylab = "Precent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )
```

```{r}
data.scaled <- scale(wisc.data)
data.dist <- dist(data.scaled)
wisc.hclust <- hclust(data.dist, method = "complete")
plot(wisc.hclust)
abline(h=19.4, col="red", lty=2)
```

```{r}
plot(wisc.pr$x[,1],wisc.pr$x[,2], col=diagnosis+1)
```

```{r}
pc.dist <- dist(wisc.pr$x[,1:3])
pc.hclust <- hclust(pc.dist, method="ward.D2")
plot(pc.hclust)
```



```{r}
grps <- cutree(pc.hclust, k=2)
table(grps,diagnosis)
plot(wisc.pr$x[,1:2], col=grps)
```


```{r}
new <- read.csv("new_samples.csv")
npc <- predict(wisc.pr, newdata=new)
npc
```

```{r}
plot(wisc.pr$x[,1:2], col=grps)
points(npc[,1], npc[,2], col="blue", pch=16)
```

