---
title: "Class08"
author: "Zhuohang Wu"
date: "February 5, 2019"
output:
  word_document: default
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Generate some example data for clustering
tmp <- c(rnorm(30,-3), rnorm(30,3))
x <- cbind(x=tmp, y=rev(tmp))
plot(x)
```

```{r}
y <- kmeans(x,centers = 5,nstart = 30)
y
y$betweenss
?kmeans
plot(x,col=y$cluster)
```


##Hierarchical clastering
```{r}
# First we need to calculate point (dis)similarity
# as the Euclidean distance between observations
dist_matrix <- dist(x)
# The hclust() function returns a hierarchical
# clustering model
hc <- hclust(d = dist_matrix)
# the print method is not so useful here
hc 
```



```{r}
d <- dist_matrix
# Using different hierarchical clustering methods
hc.complete <- hclust(d, method="complete")
plot(hc.complete)

hc.average <- hclust(d, method="average")
plot(hc.average)

hc.single <- hclust(d, method="single")
plot(hc.single)
```


```{r}
# Step 1. Generate some example data for clustering
x <- rbind(
 matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2), # c1
 matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
 matrix(c(rnorm(50, mean = 1, sd = 0.3), # c3
 rnorm(50, mean = 0, sd = 0.3)), ncol = 2))
colnames(x) <- c("x", "y")
# Step 2. Plot the data without clustering
plot(x)
# Step 3. Generate colors for known clusters
# (just so we can compare to hclust results)
col <- as.factor( rep(c("c1","c2","c3"), each=50) )
plot(x, col=col)
View(x)
```

```{r}
hc <- hclust(dist(x))
plot(hc)
cutree(hc, h=2)
abline(h=2,col="blue")
```



```{r}
mydata <- read.csv("https://tinyurl.com/expression-CSV",
 row.names=1)
head(mydata)
```

```{r}
## lets do PCA
pca <- prcomp(t(mydata), scale=TRUE) 
attributes(pca)
plot(pca$x[,1],pca$x[,2])
```

```{r}
## Variance captured per PC
pca.var <- pca$sdev^2 
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
barplot(pca.var.per, main="Scree Plot",
 xlab="Principal Component", ylab="Percent Variation")
```

```{r}
colvec <- colnames(mydata)
colvec[grep("wt", colvec)] <- "red"
colvec[grep("ko", colvec)] <- "blue"
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16,
 xlab=paste0("PC1 (", pca.var.per[1], "%)"),
 ylab=paste0("PC2 (", pca.var.per[2], "%)")) 
```

